config/routes.rb
GDP::Application.routes.draw do

  root :to => 'root#show'

  resources :shows do
    resources :pictures
    member do get 'info' end
  end
  
  resources :venues, :pages, :links, :socials
  
  resources :about, :only => :index
  match '/shows/:show_id/pictures/:id/:direction' => 'pictures#show', as: 'swap_picture_path', via: :get

  match 'change_background/:mode(/:id)' => 'application#change_background'

  resources :sessions, :only => :create
  match 'login' => 'sessions#new'
  match 'logout' => 'sessions#destroy'

  match 'mobile/on' => 'mobile#on'
  match 'mobile/off' => 'mobile#off'
    
  match 'contact' => 'contact#new', :as => 'contact', :via => :get
  match 'contact' => 'contact#create', :as => 'contact', :via => :post
  

end

app/models/picture.rb
class Picture < ActiveRecord::Base

  belongs_to :show

  validates_presence_of :alt
  validates_presence_of :show_id
  #validates_presence_of :cover_photo_ind

  validates_attachment_presence :picture

  has_attached_file :picture,
    :path => "pictures/:style/:id/:filename",
    :styles => {
       :original => "1024x800",
       :mobile => "500x400",
       :thumb  => "250x250",
       :tiny => "100x100"}

  def as_json(mobile = false, options = nil)
    picture_photographer = photographer.presence || show.photographer
    data = { id: self.id, 
             show_id: show.id.to_s,
             caption: self.caption,
             photographer: if picture_photographer.presence then 'Photo Credit: ' + picture_photographer end,
             start_date: show.formatted_start_date,
             title: show.title,
             url: if mobile then picture.url(:thumb) else picture.url end }
     
    data[:has_others] = Picture.has_other_picture(show) unless mobile
    
    data
  end
  
  def traverse(direction)
    index = show.pictures.index(self)
    case(direction.to_sym)
    when :prev then show.pictures[index-1]
    when :next then show.pictures[index+1] || show.pictures[0]
    end
  end

  def self.find(id, direction = nil)
    picture = super(id)
    if direction then picture.traverse(direction) else picture end
  end

  def self.has_other_picture(show)
    if(show == nil)
      self.where(cover_photo_ind: true).count > 1
    else
      show.pictures.where(cover_photo_ind: true).count > 1
    end
  end
  
  private 
  
  def self.random(show, current)
    if (show == nil)
      self.where(:cover_photo_ind => true)
      .where('id NOT IN (?)', current || -1)
      .first(:order => "RANDOM()")
    else
      show.pictures.where(:cover_photo_ind => true)
      .where('id NOT IN (?)', current || -1)
      .first(:order => "RANDOM()")
    end
  end

end

app/controllers/pictures_controller.rb
class PicturesController < ScaffoldController
  
  before_filter :get_show
  
  def new
    @picture = Picture.new
    @show = Show.find(params[:show_id])
  end

  def index
    @thumb_size = :thumb
    respond_to do |format|
      format.html
    end
  end

  def show

    @picture = Picture.find(params[:id], params[:direction])
    @footer = false

    respond_to do |format|
      format.html # show.html.erb
      format.js { render 'show', locals: { instant: false, picture: @picture.as_json(session[:mobile]) } }
    end
  end

  def create
    @picture = Picture.new(params[:picture].merge(show_id: @show.id))
    respond_to do |format|
      if @picture.save
        format.html { redirect_to [@show, @picture], notice: success_notice }
      else
        format.html { render action: :new }
      end
    end
  end

  private
  
  def get_show
    @show = Show.find(params[:show_id])
    @background = Background.new session[:mobile], params[:show_id]
  end
  
end

app/helpers/picture_helper.rb
module PictureHelper

  def swap_picture_path(show_id, picture_id, direction)
    "/shows/#{show_id}/pictures/#{picture_id}/#{direction}"
  end
  
end
  

app/views/pictures/_form.html.erb
<%= form_for @picture, url: show_pictures_url, html: {:multipart => true } do |f| %>
  <div class="field">
  	for <%= @show.title %>		
  </div>
  <% if @picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@picture.errors.count, "error") %> prohibited this picture from being saved:</h2>

      <ul>
      <% @picture.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
  	<%= f.label :picture, "Picture to upload" %>
    <%= f.file_field :picture %>
  </div>
  <div class="field">
    <%= f.label :alt %><br />
    <%= f.text_field :alt %>
  </div>
  <div class="">
  </div>
  <div class="field">
    <%= f.label :caption %><br />
    <%= f.text_field :caption %>
  </div>
  <div class="field">
        <%= f.label 'Cover Photo?' %><br/>
        <%= f.radio_button :cover_photo_ind, 'true' %> True<br/>
        <%= f.radio_button :cover_photo_ind, 'false' %> False
  </div>
  <div class="field">
    <%= f.label :photographer %><br />
    <%= f.text_field :photographer %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pictures/_picture_data.html.erb
<%= image_tag picture[:url], alt: picture[:alt], class: 'pictureView' %>
<%= content_tag :div, '', class: 'pictureData' do %>
	<%= render partial: 'partials/picture_data', locals: { picture: picture } %>
<% end %>
<%= content_tag :div, '', class: 'pictureMat' %>
<%= link_to image_tag('/assets/chevron_left.png'), swap_picture_path(picture[:show_id], picture[:id], :prev), remote: !mobile?, class: 'pictureArrow picturePrev' %>
<%= link_to image_tag('/assets/chevron_right.png'), swap_picture_path(picture[:show_id], picture[:id], :next), remote: !mobile?, class: 'pictureArrow pictureNext' %>

app/views/pictures/edit.html.erb
<h1>Editing picture</h1>

<%= render 'form' %>

<%= link_to 'Show', show_picture_url %> |
<%= link_to 'Back', show_pictures_path %>

app/views/pictures/index.html.erb
<% if @show && !@show.pictures.empty? %>
	<div id="galleryThumbs">
		<% @show.pictures.each do |p| %>
			<span id="showGalleryImage<%= p.id %>" class="showGalleryImage">
				<%= link_to image_tag(p.picture.url(@thumb_size || :thumb), class: "thumbnail#{' lazy-load' if @platform == 'desktop'}"), show_picture_path(@show.id, p.id), remote: !mobile?, class: 'thumbImage' %>
			</span>
		<% end %>
	</div>
	<div id="galleryViewport" class="hidden">
		<%= image_tag 'loading.gif', alt: 'Loading. . .', class: 'loading'%>
		<div class="pictureWrapper"></div>
	</div>
	<div id="hideGalleryLink" class="back-button roundFont"><%= link_to 'Back', show_path(@show.id) %></div>
<% end %>

app/views/pictures/new.html.erb
<h1>New picture</h1>

<%= render 'form' %>

<%= link_to 'Back', show_pictures_path %>

app/views/pictures/show.html.erb
<%= image_tag @picture.picture.url(:original)%>
<div class="back-button roundFont"><%= link_to 'Back', show_pictures_url(@picture.show.id) %></div>

app/views/pictures/show.js.erb
var html = '<%= escape_javascript(render partial: 'picture_data', locals: { picture: picture }) %>';
var viewport = $('#galleryViewport');
var wrapper = viewport.find('.pictureWrapper');
var loading = viewport.find('.loading');
var image = new Image();

image.onload = function() {
	wrapper.html(html).show();
	loading.hide();
	Desktop.reinitializeScroller(viewport);
};
image.src = '<%= picture[:url] %>';