config/routes.rb
GDP::Application.routes.draw do

  root :to => 'root#show'

  resources :shows do
    resources :pictures
    member do get 'info' end
  end
  
  resources :venues, :pages, :links, :socials
  
  resources :about, :only => :index
  match '/shows/:show_id/pictures/:id/:direction' => 'pictures#show', as: 'swap_picture_path', via: :get

  match 'change_background/:mode(/:id)' => 'application#change_background'

  resources :sessions, :only => :create
  match 'login' => 'sessions#new'
  match 'logout' => 'sessions#destroy'

  match 'mobile/on' => 'mobile#on'
  match 'mobile/off' => 'mobile#off'
    
  match 'contact' => 'contact#new', :as => 'contact', :via => :get
  match 'contact' => 'contact#create', :as => 'contact', :via => :post
  

end

app/models/show.rb
class Show < ActiveRecord::Base
  
  has_many :pictures              
  belongs_to :venue

  validates_presence_of :title 
  validates_presence_of :start_date 
  validates_presence_of :end_date
  validates_presence_of :description
  validates_presence_of :blurb
  validates_presence_of :venue_id
  validates_attachment_presence :thumb

  has_attached_file :thumb,
    :path => "thumbs/:style/:id/:filename",
    :styles => {:thumb=> "250x250#"},
    :default_url => "/images/missing-#{ENV['LOCALE'].downcase}.jpg"


  scope :history, -> { order(start_date: :desc) }

  def formatted_start_date
    self.start_date.strftime("%b %Y").tr('0', 'O')
  end

  def self.current
    upcoming = where("shows.end_date > ?", Time.new).order('shows.end_date ASC')
    if (upcoming.any?)
      upcoming.first
    else
      hiatus
    end
  end
  
  def self.hiatus
    hiatus = case ENV['LOCALE']
    when 'US' then { title: 'We\'ve gone international!', 
                     blurb: 'We\'re currently off in Wellington, New Zealand, doing some really cool stuff! ' + 
                    'Be sure to check it out, and watch this space for news, we\'ll be back stateside with ' +
                    'more fast, twisted, cool, cheap theater soon.' }
    when 'NZ' then { title: 'Stay tuned!', 
                     blurb: 'We\'ve got more fast, twisted, cool, cheap theater in the pipeline, watch this space!' }
    end
    Show.new hiatus if hiatus
  end
  
  def self.thumb
    image_tag self.thumb.url(:thumb)
  end
  
  def column_count
    count = self.pictures.count
    if count > 6
      3
    elsif count > 1
      2
    else
      1
    end
  end
  
end

app/controllers/shows_controller.rb
class ShowsController < ScaffoldController
  
  before_filter :one_show, :only => [:show, :page]
  
  def index
    @title = 'Our Productions'
    @shows = Show.history
    super
  end

  def show
    @show = params[:id] == 'current' ? Show.current : Show.find(params[:id])
    @title = @show.title
    super
  end

  def create
    @title = 'Create a new show'
    super
  end

  def update
    @title = 'Update a show'
    super
  end
  
  def info
    @show = Show.find(params[:id])
    respond_to do |format|
      format.html
    end
  end
  
  private

  def one_show
    mode = (params[:id] == 'current' and @current.end_date.nil?) ? 'any' : params[:id]
    @background = Background.new session[:mobile], mode
  end
  
end

app/helpers/show_helper.rb
module ShowHelper

  def show_info_url(id)
    "/shows/#{id}/info"
  end
  
end
  

app/views/shows/_desktop.html.erb
<div class="showPage">
  <% if @show.start_date.present? and @show.end_date.present? %>
  	<div id="showHeaderDates"><%= @show.start_date.strftime("%b %e").tr('0', 'O') %> - <%= @show.end_date.strftime("%b %e %Y").tr('0', 'O') %></div>
  <% end %>
  <div class="showHeader rounded clearfix">
  	<div id="showInfo">
  		<% if @show.venue.present? %>
		    <div id="mapInfo" class="showMapInfo">
		      <%= @show.venue.name %><br/>
		      <%= @show.venue.address.tr('0', 'O') %><br/>
		    </div>
		<% else %>
			<div id="showBlurb"><%= @show.blurb %></div>
	    <% end %>
	    <div id="showThumb"><%= image_tag @show.thumb.url(:thumb) %></div>
	    <div id="showMap" class="showMap"></div>
	    <% if @show.pictures.any? %>	
      	  <div id="showGalleryLink"><%= link_to (image_tag '/assets/viewGallery.png'), 'javascript:;' %></div>
	    <% end %>
    </div>
	<div id="showGallery" class="hidden"><%= render template: 'pictures/index' %></div>
  </div>
  <% if @show.venue.present? %>
  	<div id="showDescription"><%= raw RedCloth.new(@show.description).to_html %></div>
  <% end %>
</div>

app/views/shows/_form.html.erb
<%= form_for @show, :html => {:multipart => true} do |f| %>
  <% if @show.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@show.errors.count, "error") %> prohibited this show from being saved:</h2>

      <ul>
      <% @show.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br />
    <%= f.date_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br />
    <%= f.date_select :end_date %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :blurb %><br />
    <%= f.text_field :blurb %>
  </div>  
  <div class="field">
  	<%= f.label :venue_id %>
  	<%= f.collection_select(:venue_id, Venue.all, :id, :name) %>
  </div>
  <div class="field">
    <%= f.label :thumb %><br />
    <%= f.file_field :thumb %>
  </div>
  <div class="field">
    <%= f.label :photographer %><br />
    <%= f.text_field :photographer %>
  </div>
  <div class="field">
    <%= f.label :ticket_link %><br />
    <%= f.text_field :ticket_link %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shows/_mini.erb
<% default_link ||= shows_path %>
<div id="show<%= show.id %>" class="show rounded hover">
	<div class="showPic">
		<%= link_to image_tag(show.thumb.url(:thumb), :class => 'rounded'), '/shows/' + show.id.to_s %>
	</div>	
        <div class="showText">
		<div class="showTitle hover">
			<h2>
			  <%= link_to(show.title, show.persisted? ? "/shows/" + show.id.to_s() : default_link) %></h2>
			</h2>
			<%= (show.ticket_link.present? && show.end_date >= Date.today) ? link_to('(Buy Tickets)', show.ticket_link) : '' %>
        </div>
        <% if show.start_date && show.end_date %>
			<div class="showDates">
				<h2><%= show.start_date.strftime("%b %d") %> - <%= show.end_date.strftime("%b %d, %Y") %> at <%= show.venue.name %></h2>
			</div>
		<% end %>
       	<div class="showDesc"><%= show.blurb %></div>
	</div>
</div>

app/views/shows/_mobile.html.erb
<div class="showPage invisible">
  <div class="showText">
    <div class="showTitle"><h2><%= link_to(@show.title, "/shows/" + @show.id.to_s()) %></h2></div>
    <div class="showDesc"><%= @show.blurb %></div>
    <% if @show.start_date.present? and @show.end_date.present? %>
    	<div class="showDates"><h2><%= @show.start_date.strftime("%b %d") %> - <%= @show.end_date.strftime("%b %d, %Y") %> at <%= @show.venue.name %></h2></div>
  	<% end %>
  </div>
  <div class="showHeader rounded">
    <div class="showGrid roundFont">
      <%= render :partial => 'square', :locals => {
                 :name => 'Tickets',
                 :href => @show.ticket_link,
                 :icon => 'barcode',
                 :condition => !@show.ticket_link.present? && @show.end_date.present? && @show.end_date >= Date.today
      } %>
      <%= render :partial => 'square', :locals => {
                 :name => 'Map',
                 :href => 'http://www.maps.google.com/?q=' + URI::encode("#{@show.venue.address if @show.venue.present?}"),
                 :icon => 'flag',
                 :condition => @show.venue.present?
      } %>
      <%= render :partial => 'square', :locals => {
                 :name => 'Pics',
                 :href => "#{show_pictures_url(@show.id) if @show.pictures.any?}",
                 :icon => 'camera',
                 :condition => @show.pictures.any?
      } %>
      
      <%= render :partial => 'square', :locals => {
                 :name => 'Info',
                 :href => show_info_url(@show.id),
                 :icon => 'info-sign',
                 :condition => @show.description.present?
      } %>
    </div>
    <div class="backButton roundFont hidden">Back</div>
    <%= image_tag @show.thumb.url(:thumb), :class => 'showGridBack' %>
  </div>
</div>

app/views/shows/_square.html.erb
<% if condition %> 
  <div data-target="show<%= name %>"  class="showGridSquare">
    <div class="gridSquareSpacer">
      <a href="<%= !href.empty? ? href : '/shows/' + @show.id.to_s + '/' + name.downcase %>">
        <% if icon %>
          <i class="icon-<%= icon %>"></i>
        <% end %>
          <span><%= name %></span>
      </a>
    </div>
  </div>

  <div id="show<%= name %>" class="showGridCanvas offscreen"></div>
<% end %>

app/views/shows/edit.html.erb
<%= render 'form' %>

<%= link_to 'Show', @show %> |
<%= link_to 'Back', shows_path %>

app/views/shows/index.html.erb
<% @shows.each do |show| %>
  <%= render :partial => 'mini', :locals => {:show => show} %>
<% end %>

app/views/shows/info.html.erb
<%= raw RedCloth.new(@show.description).to_html %>
<div class="back-button roundFont"><%= link_to 'Back', show_path(@show.id) %></div>

app/views/shows/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', shows_path %>

app/views/shows/show.html.erb
<% if @show.venue.present? and @show.venue.latitude.present? and @show.venue.longitude.present? %>
  <div id="latlng" class="hidden"><%= @show.venue.latitude + ';' + @show.venue.longitude %></div>
<% end %>
  
<% if @show.ticket_link.present? && @show.end_date >= Date.today %>
  <div id="ticketLink" class="hidden"><%=  @show.ticket_link %></div>
<% end %>

<%= render :partial => @platform %>  

<% if session[:id] %>
  <%= link_to 'Edit', edit_show_path(@show) if @show.persisted? %> |
  <%= link_to 'Back', shows_path %>
<% end %>